export const API_ROUTES = {
  AUTH: {
    SIGNUP: '/auth/signup',
    LOGIN: '/auth/login',
    LOGOUT: '/auth/logout',
    REFRESH: '/auth/refresh',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    SESSIONS: '/auth/sessions',
  },
  USERS: {
    ME: '/users/me',
    UPDATE_PROFILE: '/users/me',
    CHANGE_PASSWORD: '/users/me/password',
  },
  ACCOUNTS: '/accounts',
  TRANSACTIONS: '/transactions',
  CATEGORIES: '/categories',
  IMPORTS: '/imports',
  BUDGETS: '/budgets',
  GOALS: '/goals',
  INVESTMENTS: '/investments',
  NET_WORTH: {
    CURRENT: '/net-worth/current',
    HISTORY: '/net-worth/history',
    CASH_FLOW: '/net-worth/cash-flow',
    SPENDING: '/net-worth/spending',
  },
  AUDIT: '/audit',
  FORECASTS: '/forecasts',
  RETIREMENT: '/retirement',
  AI: {
    STATUS: '/ai/status',
    CHAT: '/ai/chat',
    CONVERSATIONS: '/ai/conversations',
  },
  INSIGHTS: '/insights',
  NOTIFICATIONS: '/notifications',
  CATEGORIZATION: '/categorization/rules',
  ADMIN: {
    HEALTH: '/admin/health',
    STATS: '/admin/stats',
    USERS: '/admin/users',
    QUEUES: '/admin/queues',
    AUDIT: '/admin/audit',
  },
} as const;
